### ISSUE TITLE
The code is not giving output as shown in image folder

### ISSUE THREAD

**Issue by helloansuman** [developershutt/CGAN#1]
There is something missing in this code.

**Comment by developershutt** [comment]
@helloansuman please make sure that a folder name "images/" exists in your working directory. In addition, I will update the code

**Comment by helloansuman** [comment]
The folder is there. The code is running till the end up to 49000. But the output images from the codes are having noisy images and not at all looking like your output. For your kind reference last image is attached [here](https://drive.google.com/file/d/19gnlBcRYZoxU-WdJ3F4Aufoa9fHVkplh/view?usp=sharing). I think you need to update some parameters. 

Waiting for your response.

**Comment by developershutt** [comment]
> The folder is there. The code is running till the end up to 49000. But the output images from the codes are having noisy images and not at all looking like your output. For your kind reference last image is attached [here](https://drive.google.com/file/d/19gnlBcRYZoxU-WdJ3F4Aufoa9fHVkplh/view?usp=sharing). I think you need to update some parameters. 
> 
> Waiting for your response. 

Please send your notebook at huttofdevelopers@gmail.com

**Comment by helloansuman** [comment]
I have sent it. I have not changed anything in your notebook. Please check it. 
Thank you for fast reply.

**Comment by helloansuman** [comment]
The developer has fixed the problem. Thank you for your prompt reply.
